version: '3'

tasks:
  build:
    desc: Build all Docker containers
    cmds:
      - docker compose build

  up:
    desc: Start all services in detached mode
    cmds:
      - docker compose up -d

  up-logs:
    desc: Start all services and follow logs
    cmds:
      - docker compose up

  down:
    desc: Stop and remove all containers
    cmds:
      - docker compose down

  stop:
    desc: Stop all running containers
    cmds:
      - docker compose stop

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  clean:
    desc: Stop containers and remove volumes
    cmds:
      - docker compose down -v

  rebuild:
    desc: Clean rebuild - stop, remove, build, and start
    cmds:
      - task: down
      - task: build
      - task: up
